const fs = require('fs');
const ver = '1.2.18';
let p = JSON.parse(fs.readFileSync('package.json', 'utf8'));
p.version = ver;
fs.writeFileSync('package.json', JSON.stringify(p, null, 2) + '\n', 'utf8');
let sp = JSON.parse(fs.readFileSync('apps/server/package.json', 'utf8'));
sp.version = ver;
fs.writeFileSync('apps/server/package.json', JSON.stringify(sp, null, 2) + '\n', 'utf8');
let wp = JSON.parse(fs.readFileSync('apps/web/package.json', 'utf8'));
wp.version = ver;
fs.writeFileSync('apps/web/package.json', JSON.stringify(wp, null, 2) + '\n', 'utf8');
let vj = JSON.parse(fs.readFileSync('apps/server/data/version.json', 'utf8'));
vj.version = 'v' + ver;
fs.writeFileSync('apps/server/data/version.json', JSON.stringify(vj, null, 2) + '\n', 'utf8');
let readme = fs.readFileSync('README.md', 'utf8');
const entry = '### v' + ver + ' (2026-06-24)\n- **推送测试重构** \u2014 测试和保存完全分离：测试只验证凭证，不保存；保存才写入数据库\n- **测试接口支持 body config** \u2014 后端测试端点支持从请求体传入配置，不再依赖 DB 已有数据\n\n';
readme = readme.replace('## \u66f4\u65b0\u65e5\u5fd7\n\n', '## \u66f4\u65b0\u65e5\u5fd7\n\n' + entry);
fs.writeFileSync('README.md', readme, 'utf8');
console.log('done ' + ver);
